################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
ti/sensors/bme280.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/bme280.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/bme280.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/bme280_support.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/bme280_support.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/bme280_support.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/bmi160.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/bmi160.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/bmi160.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/bmi160_support.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/bmi160_support.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/bmi160_support.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/bmx_utils.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/bmx_utils.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/bmx_utils.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/i2c_driver.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/i2c_driver.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/i2c_driver.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/opt3001.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/opt3001.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/opt3001.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/tmp006.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/tmp006.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/tmp006.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/sensors/tmp007.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/sensors/tmp007.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/sensors/tmp007.d" --obj_directory="ti/sensors" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


