################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
ti/graphics/button.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/button.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/button.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/checkbox.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/checkbox.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/checkbox.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/circle.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/circle.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/circle.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/context.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/context.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/context.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/display.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/display.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/display.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/fontfixed6x8.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/fontfixed6x8.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/fontfixed6x8.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/image.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/image.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/image.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/imageButton.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/imageButton.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/imageButton.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/line.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/line.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/line.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/radioButton.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/radioButton.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/radioButton.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/rectangle.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/rectangle.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/rectangle.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/graphics/string.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/graphics/string.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/graphics/string.d" --obj_directory="ti/graphics" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


