################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
ti/msp432/adc14.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/adc14.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/adc14.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/aes256.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/aes256.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/aes256.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/comp_e.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/comp_e.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/comp_e.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/cpu.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/cpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/cpu.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/crc32.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/crc32.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/crc32.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/cs.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/cs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/cs.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/dma.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/dma.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/flash.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/flash.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/flash.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/fpu.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/fpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/fpu.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/gpio.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/gpio.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/i2c.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/i2c.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/i2c.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/interrupt.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/interrupt.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/interrupt.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/mpu.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/mpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/mpu.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/pcm.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/pcm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/pcm.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/pmap.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/pmap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/pmap.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/pss.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/pss.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/pss.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/ref_a.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/ref_a.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/ref_a.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/reset.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/reset.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/reset.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/rtc_c.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/rtc_c.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/rtc_c.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/spi.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/spi.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/sysctl.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/sysctl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/sysctl.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/systick.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/systick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/systick.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/timer32.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/timer32.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/timer32.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/timer_a.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/timer_a.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/timer_a.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/uart.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/uart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/uart.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

ti/msp432/wdt_a.obj: /home/marius/Work/UOC/PECs/scf_pec5/ti/msp432/wdt_a.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/freertos/cortex-m4" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/board" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/oslib" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/include" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cc3100/simplelink/source" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/cmsis" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/graphics" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/inc" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/lcd" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/msp432" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/ti/sensors" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_cc3100_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_edu_boosterpack" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/uoc/ti_msp432_launchpad" --include_path="/home/marius/Work/UOC/PECs/scf_pec5/projects/PEC5_1" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include" --include_path="/home/marius/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="/home/marius/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/wdt_a.d" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


